#define IDI_BOOTSTRAPPER                2
#define IDS_INSTALLHOST                 104
#define IDS_BASEHOST                    105
#define IDD_MAIN                        130
#define IDR_ACCELERATOR                 131
#define IDC_PROGRESS                    1001
#define IDC_MESSAGE                     1002
#define IDC_INSTALLSUCCESS1				1011
#define IDC_INSTALLSUCCESS2				1012
