//
//  RobloxNotifications.h
//  RobloxMobile
//
//  Created by Ariel Lichtin on 5/22/14.
//  Copyright (c) 2014 ROBLOX. All rights reserved.
//

#import <Foundation/Foundation.h>

// Login and Sign Up
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_SIGNUP_COMPLETED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_LOGGED_OUT;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_LOGIN_SUCCEEDED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_LOGIN_FAILED;

//Search
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_SEARCH_GAMES;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_SEARCH_USERS;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_USER_SELECTED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_GAME_SELECTED;

//Games
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_GAME_JOINED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_GAME_PURCHASED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_GAME_ITEMS_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_DID_LEAVE_GAME;

// Messages and System Notifications
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_FRIENDS_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_FOLLOWING_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_READ_MESSAGE;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_INBOX_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_FRIEND_REQUESTS_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_NEW_MESSAGES_TOTAL;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_NEW_FRIEND_REQUESTS_TOTAL;

//PlaceLauncher
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_GAME_DID_LEAVE;
FOUNDATION_EXPORT NSString *const RBX_NOTIFY_GAME_START_LEAVING;
FOUNDATION_EXPORT NSString *const RBX_NOTIFY_GAME_FINISHED_LOADING;
FOUNDATION_EXPORT NSString *const RBX_NOTIFY_GAME_BOUND_VIEWS;


// Other
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_ROBUX_UPDATED;
FOUNDATION_EXPORT NSString* const RBX_NOTIFY_FFLAGS_UPDATED;