#pragma once

template <class T>
class CProxy_ILauncherEvents : public IConnectionPointImpl<T, &__uuidof( _ILauncherEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
