
//**********************************************************************`
//* This is an include file generated by EtwPlusTool.                  *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
#pragma pack(push, 16)

#include "EtwPlus.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Field Descriptors, used in the ETX_EVENT_DESCRIPTOR array below
//
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_A_DeleteMe_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AvatarsEquipped_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_Award10DayRoll_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_Award20DayRoll_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_Award3DayRoll_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardDeepDiver_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardFoursCompany_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardOneNameManyFaces_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardPollster_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardSampler_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardStrengthInNumbers_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardWorldTraveler_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_AwardYouDidIt_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_CurrentAvatar_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_GameProgress_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_GamesCount_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_MultiplayerRoundEnd_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_MultiplayerRoundStart_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_PartyCount_Fields[3] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_PlayerSessionEnd_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_PlayerSessionPause_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_PlayerSessionResume_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR RBLX_1465F7BC_PlayerSessionStart_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};

// Event name mapping
//
#define A_DeleteMe_value 1
#define AvatarsEquipped_value 2
#define Award10DayRoll_value 3
#define Award20DayRoll_value 4
#define Award3DayRoll_value 5
#define AwardDeepDiver_value 6
#define AwardFoursCompany_value 7
#define AwardOneNameManyFaces_value 8
#define AwardPollster_value 9
#define AwardSampler_value 10
#define AwardStrengthInNumbers_value 11
#define AwardWorldTraveler_value 12
#define AwardYouDidIt_value 13
#define CurrentAvatar_value 14
#define GameProgress_value 15
#define GamesCount_value 16
#define MultiplayerRoundEnd_value 17
#define MultiplayerRoundStart_value 18
#define PartyCount_value 19
#define PlayerSessionEnd_value 20
#define PlayerSessionPause_value 21
#define PlayerSessionResume_value 22
#define PlayerSessionStart_value 23

// Event Descriptor array
//
EXTERN_C __declspec(selectany) ETX_EVENT_DESCRIPTOR RBLX_1465F7BCEvents[23] =  {
    {{ 1, 0, 0, 0, 0, 0, 0x0 }, "A_DeleteMe", "0.7.IGB-2.0", RBLX_1465F7BC_A_DeleteMe_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 2, 1, 0, 0, 0, 0, 0x0 }, "AvatarsEquipped", "0.7.IGB-2.1", RBLX_1465F7BC_AvatarsEquipped_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 3, 0, 0, 0, 0, 0, 0x0 }, "Award10DayRoll", "0.7.IGB-2.0", RBLX_1465F7BC_Award10DayRoll_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 4, 0, 0, 0, 0, 0, 0x0 }, "Award20DayRoll", "0.7.IGB-2.0", RBLX_1465F7BC_Award20DayRoll_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 5, 0, 0, 0, 0, 0, 0x0 }, "Award3DayRoll", "0.7.IGB-2.0", RBLX_1465F7BC_Award3DayRoll_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 6, 0, 0, 0, 0, 0, 0x0 }, "AwardDeepDiver", "0.7.IGB-2.0", RBLX_1465F7BC_AwardDeepDiver_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 7, 0, 0, 0, 0, 0, 0x0 }, "AwardFoursCompany", "0.7.IGB-2.0", RBLX_1465F7BC_AwardFoursCompany_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 8, 0, 0, 0, 0, 0, 0x0 }, "AwardOneNameManyFaces", "0.7.IGB-2.0", RBLX_1465F7BC_AwardOneNameManyFaces_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 9, 0, 0, 0, 0, 0, 0x0 }, "AwardPollster", "0.7.IGB-2.0", RBLX_1465F7BC_AwardPollster_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 10, 0, 0, 0, 0, 0, 0x0 }, "AwardSampler", "0.7.IGB-2.0", RBLX_1465F7BC_AwardSampler_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 11, 0, 0, 0, 0, 0, 0x0 }, "AwardStrengthInNumbers", "0.7.IGB-2.0", RBLX_1465F7BC_AwardStrengthInNumbers_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 12, 0, 0, 0, 0, 0, 0x0 }, "AwardWorldTraveler", "0.7.IGB-2.0", RBLX_1465F7BC_AwardWorldTraveler_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 13, 0, 0, 0, 0, 0, 0x0 }, "AwardYouDidIt", "0.7.IGB-2.0", RBLX_1465F7BC_AwardYouDidIt_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 14, 0, 0, 0, 0, 0, 0x0 }, "CurrentAvatar", "0.7.IGB-2.0", RBLX_1465F7BC_CurrentAvatar_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 15, 0, 0, 0, 0, 0, 0x0 }, "GameProgress", "0.7.IGGP-2.0", RBLX_1465F7BC_GameProgress_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 16, 0, 0, 0, 0, 0, 0x0 }, "GamesCount", "0.7.IGB-2.0", RBLX_1465F7BC_GamesCount_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 17, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundEnd", "0.7.IGMRE-2.0", RBLX_1465F7BC_MultiplayerRoundEnd_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 18, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundStart", "0.7.IGMRS-2.0", RBLX_1465F7BC_MultiplayerRoundStart_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 19, 0, 0, 0, 0, 0, 0x0 }, "PartyCount", "0.7.IGB-2.0", RBLX_1465F7BC_PartyCount_Fields, 3, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 20, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionEnd", "0.7.IGPSE-2.0", RBLX_1465F7BC_PlayerSessionEnd_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 21, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionPause", "0.7.IGPSPA-2.0", RBLX_1465F7BC_PlayerSessionPause_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 22, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionResume", "0.7.IGPSR-2.0", RBLX_1465F7BC_PlayerSessionResume_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 23, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionStart", "0.7.IGPSS-2.0", RBLX_1465F7BC_PlayerSessionStart_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault }};

// Provider Descriptor for RBLX_1465F7BC
//
EXTERN_C __declspec(selectany) ETX_PROVIDER_DESCRIPTOR RBLX_1465F7BCProvider = {"RBLX_1465F7BC", {0xc01cb476,0x5b6e,0x430d,{0xa9,0x07,0xcd,0x42,0x2e,0xfb,0x76,0x4a}}, 23, (ETX_EVENT_DESCRIPTOR*)&RBLX_1465F7BCEvents, 0, EtxProviderEnabledState_Undefined, EtxProviderEnabledState_OnByDefault, 0, 100, EtxProviderLatency_Undefined, EtxProviderLatency_RealTime, EtxProviderPriority_Undefined, EtxProviderPriority_Critical};

// ETW handle for RBLX_1465F7BC
//
EXTERN_C __declspec(selectany) REGHANDLE RBLX_1465F7BCHandle = (REGHANDLE)0;

/*++

Routine Description:

    Register the provider with ETW+.

Arguments:
    
    None

Remarks:

    ERROR_SUCCESS if success or if the provider was already registered. 
    Otherwise, an error code.

--*/
#define EventRegisterRBLX_1465F7BC() EtxRegister(&RBLX_1465F7BCProvider, &RBLX_1465F7BCHandle)

/*++

Routine Description:

    Unregister the provider from ETW+.

Arguments:
            None
Remarks:
    ERROR_SUCCESS if success or if the provider was not registered. 
    Otherwise, an error code.
--*/
#define EventUnregisterRBLX_1465F7BC() EtxUnregister(&RBLX_1465F7BCProvider, &RBLX_1465F7BCHandle)

#define EventEnabledA_DeleteMe() (TRUE)

// Entry point to log the event A_DeleteMe
//
__inline
ULONG
EventWriteA_DeleteMe(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_A_DeleteMe 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_A_DeleteMe];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[0], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_A_DeleteMe, EventData);
}
#define EventEnabledAvatarsEquipped() (TRUE)

// Entry point to log the event AvatarsEquipped
//
__inline
ULONG
EventWriteAvatarsEquipped(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int AvatarsCount)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AvatarsEquipped 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AvatarsEquipped];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &AvatarsCount, sizeof(AvatarsCount));

    return EtxEventWrite(&RBLX_1465F7BCEvents[1], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AvatarsEquipped, EventData);
}
#define EventEnabledAward10DayRoll() (TRUE)

// Entry point to log the event Award10DayRoll
//
__inline
ULONG
EventWriteAward10DayRoll(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_Award10DayRoll 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_Award10DayRoll];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[2], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_Award10DayRoll, EventData);
}
#define EventEnabledAward20DayRoll() (TRUE)

// Entry point to log the event Award20DayRoll
//
__inline
ULONG
EventWriteAward20DayRoll(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_Award20DayRoll 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_Award20DayRoll];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[3], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_Award20DayRoll, EventData);
}
#define EventEnabledAward3DayRoll() (TRUE)

// Entry point to log the event Award3DayRoll
//
__inline
ULONG
EventWriteAward3DayRoll(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_Award3DayRoll 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_Award3DayRoll];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[4], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_Award3DayRoll, EventData);
}
#define EventEnabledAwardDeepDiver() (TRUE)

// Entry point to log the event AwardDeepDiver
//
__inline
ULONG
EventWriteAwardDeepDiver(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardDeepDiver 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardDeepDiver];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[5], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardDeepDiver, EventData);
}
#define EventEnabledAwardFoursCompany() (TRUE)

// Entry point to log the event AwardFoursCompany
//
__inline
ULONG
EventWriteAwardFoursCompany(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardFoursCompany 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardFoursCompany];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[6], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardFoursCompany, EventData);
}
#define EventEnabledAwardOneNameManyFaces() (TRUE)

// Entry point to log the event AwardOneNameManyFaces
//
__inline
ULONG
EventWriteAwardOneNameManyFaces(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardOneNameManyFaces 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardOneNameManyFaces];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[7], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardOneNameManyFaces, EventData);
}
#define EventEnabledAwardPollster() (TRUE)

// Entry point to log the event AwardPollster
//
__inline
ULONG
EventWriteAwardPollster(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardPollster 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardPollster];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[8], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardPollster, EventData);
}
#define EventEnabledAwardSampler() (TRUE)

// Entry point to log the event AwardSampler
//
__inline
ULONG
EventWriteAwardSampler(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardSampler 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardSampler];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[9], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardSampler, EventData);
}
#define EventEnabledAwardStrengthInNumbers() (TRUE)

// Entry point to log the event AwardStrengthInNumbers
//
__inline
ULONG
EventWriteAwardStrengthInNumbers(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardStrengthInNumbers 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardStrengthInNumbers];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[10], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardStrengthInNumbers, EventData);
}
#define EventEnabledAwardWorldTraveler() (TRUE)

// Entry point to log the event AwardWorldTraveler
//
__inline
ULONG
EventWriteAwardWorldTraveler(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardWorldTraveler 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardWorldTraveler];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[11], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardWorldTraveler, EventData);
}
#define EventEnabledAwardYouDidIt() (TRUE)

// Entry point to log the event AwardYouDidIt
//
__inline
ULONG
EventWriteAwardYouDidIt(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_AwardYouDidIt 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_AwardYouDidIt];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[12], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_AwardYouDidIt, EventData);
}
#define EventEnabledCurrentAvatar() (TRUE)

// Entry point to log the event CurrentAvatar
//
__inline
ULONG
EventWriteCurrentAvatar(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_CurrentAvatar 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_CurrentAvatar];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[13], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_CurrentAvatar, EventData);
}
#define EventEnabledGameProgress() (TRUE)

// Entry point to log the event GameProgress
//
__inline
ULONG
EventWriteGameProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const float CompletionPercent)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_GameProgress 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_GameProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &CompletionPercent, sizeof(CompletionPercent));

    return EtxEventWrite(&RBLX_1465F7BCEvents[14], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_GameProgress, EventData);
}
#define EventEnabledGamesCount() (TRUE)

// Entry point to log the event GamesCount
//
__inline
ULONG
EventWriteGamesCount(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_GamesCount 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_GamesCount];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[15], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_GamesCount, EventData);
}
#define EventEnabledMultiplayerRoundEnd() (TRUE)

// Entry point to log the event MultiplayerRoundEnd
//
__inline
ULONG
EventWriteMultiplayerRoundEnd(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId, __in const float TimeInSeconds, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundEnd 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[9], &TimeInSeconds, sizeof(TimeInSeconds));
    EventDataDescCreate(&EventData[10], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&RBLX_1465F7BCEvents[16], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundEnd, EventData);
}
#define EventEnabledMultiplayerRoundStart() (TRUE)

// Entry point to log the event MultiplayerRoundStart
//
__inline
ULONG
EventWriteMultiplayerRoundStart(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundStart 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&RBLX_1465F7BCEvents[17], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_MultiplayerRoundStart, EventData);
}
#define EventEnabledPartyCount() (TRUE)

// Entry point to log the event PartyCount
//
__inline
ULONG
EventWritePartyCount(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_PartyCount 3

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_PartyCount];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));

    return EtxEventWrite(&RBLX_1465F7BCEvents[18], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_PartyCount, EventData);
}
#define EventEnabledPlayerSessionEnd() (TRUE)

// Entry point to log the event PlayerSessionEnd
//
__inline
ULONG
EventWritePlayerSessionEnd(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionEnd 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[6], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&RBLX_1465F7BCEvents[19], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionEnd, EventData);
}
#define EventEnabledPlayerSessionPause() (TRUE)

// Entry point to log the event PlayerSessionPause
//
__inline
ULONG
EventWritePlayerSessionPause(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionPause 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionPause];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&RBLX_1465F7BCEvents[20], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionPause, EventData);
}
#define EventEnabledPlayerSessionResume() (TRUE)

// Entry point to log the event PlayerSessionResume
//
__inline
ULONG
EventWritePlayerSessionResume(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionResume 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionResume];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&RBLX_1465F7BCEvents[21], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionResume, EventData);
}
#define EventEnabledPlayerSessionStart() (TRUE)

// Entry point to log the event PlayerSessionStart
//
__inline
ULONG
EventWritePlayerSessionStart(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionStart 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&RBLX_1465F7BCEvents[22], &RBLX_1465F7BCProvider, RBLX_1465F7BCHandle, ARGUMENT_COUNT_RBLX_1465F7BC_PlayerSessionStart, EventData);
}
#if defined(__cplusplus)
};
#endif

#pragma pack(pop)
