include_directories("${CMAKE_SOURCE_DIR}/Base/include")
include_directories("${CMAKE_SOURCE_DIR}/Log/include")
if(ANDROID)
  include_directories("${CMAKE_SOURCE_DIR}/Base/include/rbx/Android")
endif(ANDROID)
